### ISSUE TITLE
File missing from backup

### ISSUE THREAD

**Issue by sc74** [MattBlack85/astro_monitor#23]
Hi,

Would it be possible to include the fov.dat file in the backup?

Clear sky

Stéphane

**Comment by MattBlack85** [comment]
what kind of data fov.dat contains, also, what is the full path of the file?

**Comment by sc74** [comment]
The fov.dat file contains the targets for the field of view. You can create them yourself.

It is located in ~/.local/share/kstars/fov.dat

![Screenshot_20240305_172807](https://github.com/MattBlack85/astro_monitor/assets/7612483/41da2f82-8849-4d34-9318-ea4eee8494c1)

![Screenshot_20240305_173501](https://github.com/MattBlack85/astro_monitor/assets/7612483/a7b104a0-b7b7-4f03-b9ad-dec6404ec52f)

**Comment by MattBlack85** [comment]
fixed via 31198dfedc7b32b1de417d375c59c9d7c58166dc

**Comment by teoteo** [comment]
If you think to manage it, on MacOs the path is `~/Library/Application%20Support/kstars/fov.dat`

**Comment by MattBlack85** [comment]
Aight aight, forgot about apples. Gonna fix it soon
