### ISSUE TITLE
Wrong release version on macOS?

### ISSUE THREAD

**Issue by teoteo** [MattBlack85/astro_monitor#26]
The last release on macOS declared as version 1.0.3
```
% astromonitor -V
astromonitor 1.0.3
```
are them related?
https://github.com/MattBlack85/astro_monitor/blob/12127fc9b689f2b7612dde28c10d2396e853602d/Cargo.lock#L25

**Comment by MattBlack85** [comment]
yes, I rushed and forgot to update that value before releasing

**Comment by MattBlack85** [comment]
not a "real" issue, I mean you have the new version but the app reports itself an old one cause I am dumb. Next version will fix it
